# Generated by Django 5.2.17 on 2026-08-28 17:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='分類名稱')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='網址代稱')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='已確認')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='確認碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='標籤')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='網址代稱')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='個人簡介')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='標題')),
                ('slug', models.SlugField(max_length=160, unique_for_date='published_at', verbose_name='網址代稱')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('body', models.TextField(verbose_name='內文（Markdown）')),
                ('body_html', models.TextField(blank=True, editable=False, verbose_name='內文（已渲染）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('scheduled', '已排程'), ('published', '已發佈')], default='draft', max_length=12, verbose_name='狀態')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='發佈時間')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='瀏覽次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='主要作者')),
                ('coauthors', models.ManyToManyField(blank=True, related_name='coauthored_articles', to=settings.AUTH_USER_MODEL, verbose_name='共同作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='journal.category', verbose_name='分類')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000, verbose_name='留言內容')),
                ('is_approved', models.BooleanField(default=True, verbose_name='已核准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='journal.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='journal.comment', verbose_name='回覆對象')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_order', models.PositiveSmallIntegerField(default=0, verbose_name='精選排序')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.tag')),
            ],
            options={
                'ordering': ['featured_order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', through='journal.ArticleTag', to='journal.tag', verbose_name='標籤'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('like', '讚'), ('insightful', '有收穫'), ('curious', '想知道更多')], max_length=12, verbose_name='反應')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='journal.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'user', 'kind'), name='unique_reaction')],
            },
        ),
        migrations.AddConstraint(
            model_name='articletag',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='unique_article_tag'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='journal_art_status_c545ff_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='journal_art_slug_b5ec2a_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='published_article_has_timestamp'),
        ),
    ]
