from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEXT_SUFFIXES = {".md", ".py", ".toml", ".yml", ".yaml", ".txt"}

REPLACEMENTS = [
    ("https://docs.djangoproject.com/en/5.2/", "https://docs.djangoproject.com/en/6.1/"),
    ("django>=5.2,<5.3", "django>=6.1.1,<6.2"),
    ("Django 5.2 LTS", "Django 6.1.1"),
    ("Django 5.2 系列", "Django 6.1.1 系列"),
    ("Django 5.2", "Django 6.1.1"),
    ("5.2.x", "6.1.x"),
    ("Python 3.13", "Python 3.14.7"),
    ("python 3.13", "python 3.14.7"),
    ("--python 3.13", "--python 3.14.7"),
    ("pin 3.13", "pin 3.14.7"),
    ("install 3.13", "install 3.14.7"),
    ('python-version: "3.13"', 'python-version: "3.14.7"'),
    ("python-version: '3.13'", "python-version: '3.14.7'"),
    ('requires-python = ">=3.13"', 'requires-python = ">=3.14,<3.15"'),
]

OLD_EMAIL = 'EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"'
NEW_EMAIL = '''MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
        "OPTIONS": {},
    }
}'''


def update_version_references() -> list[Path]:
    changed: list[Path] = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        if ".git" in path.parts or "migrations" in path.parts or path.name == "uv.lock":
            continue
        try:
            old = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        new = old
        for before, after in REPLACEMENTS:
            new = new.replace(before, after)
        if path.suffix.lower() == ".md":
            new = new.replace(OLD_EMAIL, NEW_EMAIL)

        if new != old:
            path.write_text(new, encoding="utf-8")
            changed.append(path.relative_to(ROOT))

    for project in ("learnboard", "learnmart", "learnjournal"):
        (ROOT / project / ".python-version").write_text("3.14.7\n", encoding="utf-8")

    return changed


def strip_frontmatter(text: str) -> str:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return text.strip()
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "\n".join(lines[index + 1 :]).strip()
    return text.strip()


def build_combined_django02() -> tuple[Path, list[Path]]:
    folder = ROOT / "slides" / "02_forms_auth_and_two_projects"
    output = folder / "02_forms_auth_and_two_projects.md"
    sources = sorted(path for path in folder.glob("*.md") if path != output)

    chunks: list[str] = []
    for index, path in enumerate(sources):
        text = path.read_text(encoding="utf-8").strip()
        if index == 0:
            chunks.append(text)
        else:
            chunks.append(
                "\n\n---\n\n"
                f"<!-- merged source: {path.name} -->\n\n"
                + strip_frontmatter(text)
            )

    output.write_text("".join(chunks).rstrip() + "\n", encoding="utf-8")
    return output.relative_to(ROOT), [path.relative_to(ROOT) for path in sources]


def append_audit_note() -> None:
    path = ROOT / "CURRICULUM_AUDIT_CHATGPT.md"
    marker = "## 10. Django 6.1.1 / Python 3.14.7 升級"
    text = path.read_text(encoding="utf-8")
    if marker in text:
        return
    note = """

## 10. Django 6.1.1 / Python 3.14.7 升級（2026-09-16）

本 branch 已將三個教學專案與教材基線升級到 **Python 3.14.7 + Django 6.1.1**。

- 三個專案的 `pyproject.toml`：`requires-python = \">=3.14,<3.15\"`、`django>=6.1.1,<6.2`
- 三份 `.python-version`：固定 `3.14.7`
- 三份 `uv.lock`：以新版依賴重新解析
- Django 官方文件連結：由 5.2 文件更新為 6.1 文件
- LearnJournal email：採 Django 6.1 `MAILERS`；不再把 `EMAIL_BACKEND` 當作目前建議設定
- CI：LearnBoard、LearnMart、LearnJournal 都以 Python 3.14.7 驗證 `check`、migration drift 與 tests
- `slides/02_forms_auth_and_two_projects/02_forms_auth_and_two_projects.md`：依檔名順序整合該資料夾全部 Markdown；保留第一份 Marp front matter，其餘 front matter 移除後串接。

> 既有 migration 頂端的 `Generated by Django 5.2.x` 是歷史 metadata，刻意保留；不應只為版本文字一致而重寫 migration 歷史。
"""
    path.write_text(text.rstrip() + note + "\n", encoding="utf-8")


def main() -> None:
    changed = update_version_references()
    output, sources = build_combined_django02()
    append_audit_note()

    print(f"Updated version references in {len(changed)} files.")
    for path in changed:
        print(f"  - {path}")
    print("Combined Django 02 sources in filename order:")
    for path in sources:
        print(f"  - {path.name}")
    print(f"Output: {output}")


if __name__ == "__main__":
    main()
